hf_configuration:
  hf_dataset_name: yourbench_example
  private: true

model_list:
  - model_name: google/gemini-2.5-flash-lite-preview-06-17
    base_url: https://openrouter.ai/api/v1
    api_key: $OPENROUTER_API_KEY

pipeline:
  ingestion:
    run: true
    source_documents_dir: example/data/raw
    output_dir: example/data/processed
    llm_ingestion: true
  # summarization:
  # chunking:
  # single_shot_question_generation:
  # multi_hop_question_generation:
  # lighteval:
  # citation_score_filtering: