pipeline:
  ingestion:
    run: true
    source_documents_dir: example/data/raw
    output_dir: example/data/processed
  # summarization:
  # chunking:
  # single_shot_question_generation:
  # multi_hop_question_generation:
  # lighteval:
  # citation_score_filtering: