hf_configuration:
  hf_dataset_name: yourbench_example_v2
  private: true

model_list:
  - model_name: mistralai/Magistral-Small-2506
    base_url: http://stargate:8000/v1
    api_key: $OPENROUTER_API_KEY

pipeline:
  ingestion:
  summarization:
  chunking:
  # single_shot_question_generation:
  # multi_hop_question_generation:
  # lighteval:
  # citation_score_filtering: