hf_configuration:
  hf_dataset_name: yourbench_example_v3
  hf_organization: yourbench
  private: false

model_list:
  - model_name: Qwen/Qwen3-30B-A3B

pipeline:
  ingestion:
  summarization:
  chunking:
  single_shot_question_generation:
  multi_hop_question_generation:
  cross_document_question_generation:
  prepare_lighteval:
  citation_score_filtering: